# -*- coding: utf-8 -*-
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""    

def fib_dict(n,d):
    if n in d:
        return  d[n]
    else:
        x=fib_dict(n-1,d)+fib_dict(n-2,d)
        d[n]=x
        return x

dct={1:1,2:2}
new={}

y=0
while True:
    y+=1
    if fib_dict(y,dct)>=4000000:
        break
    for key,value in dct.items():
        new[key]=value
t=0        
for value in new.values():
    if value%2==0:
        t+=value
print(t)
    
        
    
    
    


        
    